name: Grevm Tests

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [checks_requested]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # check out
      - name: Checkout repository
        uses: actions/checkout@v3

      # install rust tools
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        run: cargo test -- --skip mainnet
