name: Grevm Format Check

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [checks_requested]

jobs:
  fmt_check:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dsherret/rust-toolchain-file@v1

      # install nightly toolchain at the same time.
      - name: Setup rust toolchain
        shell: bash
        run: rustup toolchain install nightly

      - name: Install rustfmt
        run: rustup component add rustfmt --toolchain nightly

      - name: Run cargo fmt
        run: cargo +nightly fmt --check
